import { getEnvVariable } from 'src/utils';

const VITE_SHOW_UPDATE_CONNECTION = getEnvVariable('VITE_AMP_SHOW_UPDATE_CONNECTION', false);
const NEXT_SHOW_UPDATE_CONNECTION = getEnvVariable('NEXT_AMP_SHOW_UPDATE_CONNECTION', false);
const REACT_APP_SHOW_UPDATE_CONNECTION = getEnvVariable('REACT_APP_AMP_SHOW_UPDATE_CONNECTION', false);
export const SHOW_UPDATE_CONNECTION = !!VITE_SHOW_UPDATE_CONNECTION
|| !!NEXT_SHOW_UPDATE_CONNECTION || !!REACT_APP_SHOW_UPDATE_CONNECTION;
