/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefaultPeriodConfig } from './DefaultPeriodConfig';
import {
    DefaultPeriodConfigFromJSON,
    DefaultPeriodConfigFromJSONTyped,
    DefaultPeriodConfigToJSON,
} from './DefaultPeriodConfig';

/**
 * 
 * @export
 * @interface BackfillConfig
 */
export interface BackfillConfig {
    /**
     * 
     * @type {DefaultPeriodConfig}
     * @memberof BackfillConfig
     */
    defaultPeriod: DefaultPeriodConfig;
}

/**
 * Check if a given object implements the BackfillConfig interface.
 */
export function instanceOfBackfillConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "defaultPeriod" in value;

    return isInstance;
}

export function BackfillConfigFromJSON(json: any): BackfillConfig {
    return BackfillConfigFromJSONTyped(json, false);
}

export function BackfillConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackfillConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultPeriod': DefaultPeriodConfigFromJSON(json['defaultPeriod']),
    };
}

export function BackfillConfigToJSON(value?: BackfillConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultPeriod': DefaultPeriodConfigToJSON(value.defaultPeriod),
    };
}

