/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigContentAllOf
 */
export interface ConfigContentAllOf {
    /**
     * 
     * @type {any}
     * @memberof ConfigContentAllOf
     */
    read?: any | null;
}

/**
 * Check if a given object implements the ConfigContentAllOf interface.
 */
export function instanceOfConfigContentAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConfigContentAllOfFromJSON(json: any): ConfigContentAllOf {
    return ConfigContentAllOfFromJSONTyped(json, false);
}

export function ConfigContentAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigContentAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'read': !exists(json, 'read') ? undefined : json['read'],
    };
}

export function ConfigContentAllOfToJSON(value?: ConfigContentAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'read': value.read,
    };
}

