/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Connection } from './Connection';
import {
    ConnectionFromJSON,
    ConnectionFromJSONTyped,
    ConnectionToJSON,
} from './Connection';

/**
 * 
 * @export
 * @interface ConnectionsList
 */
export interface ConnectionsList {
    /**
     * 
     * @type {Array<Connection>}
     * @memberof ConnectionsList
     */
    connections?: Array<Connection>;
}

/**
 * Check if a given object implements the ConnectionsList interface.
 */
export function instanceOfConnectionsList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConnectionsListFromJSON(json: any): ConnectionsList {
    return ConnectionsListFromJSONTyped(json, false);
}

export function ConnectionsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connections': !exists(json, 'connections') ? undefined : ((json['connections'] as Array<any>).map(ConnectionFromJSON)),
    };
}

export function ConnectionsListToJSON(value?: ConnectionsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connections': value.connections === undefined ? undefined : ((value.connections as Array<any>).map(ConnectionToJSON)),
    };
}

