/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDestinationRequestMetadata
 */
export interface CreateDestinationRequestMetadata {
    /**
     * Webhook URL, must start with "https://".
     * @type {string}
     * @memberof CreateDestinationRequestMetadata
     */
    url?: string;
    /**
     * Additional headers to add when Ampersand sends a webhook message
     * @type {{ [key: string]: string; }}
     * @memberof CreateDestinationRequestMetadata
     */
    headers?: { [key: string]: string; } | null;
    /**
     * The AWS region where the kinesis destination is hosted.
     * @type {string}
     * @memberof CreateDestinationRequestMetadata
     */
    kinesisRegion?: string;
    /**
     * The name of the Kinesis stream to send events to.
     * @type {string}
     * @memberof CreateDestinationRequestMetadata
     */
    kinesisStreamName?: string;
    /**
     * The endpoint URL for the Kinesis stream.
     * @type {string}
     * @memberof CreateDestinationRequestMetadata
     */
    kinesisEndpointUrl?: string;
    /**
     * The template for the partition key to use when sending events to Kinesis (a JMESPath template)
     * @type {string}
     * @memberof CreateDestinationRequestMetadata
     */
    kinesisPartitionKeyTemplate?: string;
}

/**
 * Check if a given object implements the CreateDestinationRequestMetadata interface.
 */
export function instanceOfCreateDestinationRequestMetadata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateDestinationRequestMetadataFromJSON(json: any): CreateDestinationRequestMetadata {
    return CreateDestinationRequestMetadataFromJSONTyped(json, false);
}

export function CreateDestinationRequestMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDestinationRequestMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'headers': !exists(json, 'headers') ? undefined : json['headers'],
        'kinesisRegion': !exists(json, 'kinesisRegion') ? undefined : json['kinesisRegion'],
        'kinesisStreamName': !exists(json, 'kinesisStreamName') ? undefined : json['kinesisStreamName'],
        'kinesisEndpointUrl': !exists(json, 'kinesisEndpointUrl') ? undefined : json['kinesisEndpointUrl'],
        'kinesisPartitionKeyTemplate': !exists(json, 'kinesisPartitionKeyTemplate') ? undefined : json['kinesisPartitionKeyTemplate'],
    };
}

export function CreateDestinationRequestMetadataToJSON(value?: CreateDestinationRequestMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'headers': value.headers,
        'kinesisRegion': value.kinesisRegion,
        'kinesisStreamName': value.kinesisStreamName,
        'kinesisEndpointUrl': value.kinesisEndpointUrl,
        'kinesisPartitionKeyTemplate': value.kinesisPartitionKeyTemplate,
    };
}

