/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRevisionRequest
 */
export interface CreateRevisionRequest {
    /**
     * URL of where a zip of the source files can be downloaded (e.g. Google Cloud Storage URL).
     * @type {string}
     * @memberof CreateRevisionRequest
     */
    sourceZipUrl: string;
}

/**
 * Check if a given object implements the CreateRevisionRequest interface.
 */
export function instanceOfCreateRevisionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sourceZipUrl" in value;

    return isInstance;
}

export function CreateRevisionRequestFromJSON(json: any): CreateRevisionRequest {
    return CreateRevisionRequestFromJSONTyped(json, false);
}

export function CreateRevisionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRevisionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceZipUrl': json['sourceZipUrl'],
    };
}

export function CreateRevisionRequestToJSON(value?: CreateRevisionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourceZipUrl': value.sourceZipUrl,
    };
}

