/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTopicTargetRouteRequest
 */
export interface CreateTopicTargetRouteRequest {
    /**
     * The ID of the notification topic.
     * @type {string}
     * @memberof CreateTopicTargetRouteRequest
     */
    topicId: string;
    /**
     * The ID of the notification target.
     * @type {string}
     * @memberof CreateTopicTargetRouteRequest
     */
    targetId: string;
}

/**
 * Check if a given object implements the CreateTopicTargetRouteRequest interface.
 */
export function instanceOfCreateTopicTargetRouteRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "topicId" in value;
    isInstance = isInstance && "targetId" in value;

    return isInstance;
}

export function CreateTopicTargetRouteRequestFromJSON(json: any): CreateTopicTargetRouteRequest {
    return CreateTopicTargetRouteRequestFromJSONTyped(json, false);
}

export function CreateTopicTargetRouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTopicTargetRouteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topicId': json['topicId'],
        'targetId': json['targetId'],
    };
}

export function CreateTopicTargetRouteRequestToJSON(value?: CreateTopicTargetRouteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topicId': value.topicId,
        'targetId': value.targetId,
    };
}

