/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Configuration for detecting when field types change.
 * @export
 * @interface FieldTypeChangedEvent
 */
export interface FieldTypeChangedEvent {
    /**
     * If always, the integration will monitor for field type changes by default.
     * @type {string}
     * @memberof FieldTypeChangedEvent
     */
    enabled: FieldTypeChangedEventEnabledEnum;
}


/**
 * @export
 */
export const FieldTypeChangedEventEnabledEnum = {
    Always: 'always'
} as const;
export type FieldTypeChangedEventEnabledEnum = typeof FieldTypeChangedEventEnabledEnum[keyof typeof FieldTypeChangedEventEnabledEnum];


/**
 * Check if a given object implements the FieldTypeChangedEvent interface.
 */
export function instanceOfFieldTypeChangedEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;

    return isInstance;
}

export function FieldTypeChangedEventFromJSON(json: any): FieldTypeChangedEvent {
    return FieldTypeChangedEventFromJSONTyped(json, false);
}

export function FieldTypeChangedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldTypeChangedEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
    };
}

export function FieldTypeChangedEventToJSON(value?: FieldTypeChangedEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}

