/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HydratedIntegrationAction } from './HydratedIntegrationAction';
import {
    HydratedIntegrationActionFromJSON,
    HydratedIntegrationActionFromJSONTyped,
    HydratedIntegrationActionToJSON,
} from './HydratedIntegrationAction';

/**
 * 
 * @export
 * @interface HydratedIntegration
 */
export interface HydratedIntegration {
    /**
     * 
     * @type {string}
     * @memberof HydratedIntegration
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof HydratedIntegration
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof HydratedIntegration
     */
    api: string;
    /**
     * 
     * @type {Array<HydratedIntegrationAction>}
     * @memberof HydratedIntegration
     */
    actions: Array<HydratedIntegrationAction>;
}

/**
 * Check if a given object implements the HydratedIntegration interface.
 */
export function instanceOfHydratedIntegration(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "api" in value;
    isInstance = isInstance && "actions" in value;

    return isInstance;
}

export function HydratedIntegrationFromJSON(json: any): HydratedIntegration {
    return HydratedIntegrationFromJSONTyped(json, false);
}

export function HydratedIntegrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): HydratedIntegration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'api': json['api'],
        'actions': ((json['actions'] as Array<any>).map(HydratedIntegrationActionFromJSON)),
    };
}

export function HydratedIntegrationToJSON(value?: HydratedIntegration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'displayName': value.displayName,
        'api': value.api,
        'actions': ((value.actions as Array<any>).map(HydratedIntegrationActionToJSON)),
    };
}

