/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NotificationTopicTargetRoute } from './NotificationTopicTargetRoute';
import {
    NotificationTopicTargetRouteFromJSON,
    NotificationTopicTargetRouteFromJSONTyped,
    NotificationTopicTargetRouteToJSON,
} from './NotificationTopicTargetRoute';

/**
 * 
 * @export
 * @interface ListTopicTargetRoutes200Response
 */
export interface ListTopicTargetRoutes200Response {
    /**
     * 
     * @type {Array<NotificationTopicTargetRoute>}
     * @memberof ListTopicTargetRoutes200Response
     */
    topicTargetRoutes?: Array<NotificationTopicTargetRoute>;
}

/**
 * Check if a given object implements the ListTopicTargetRoutes200Response interface.
 */
export function instanceOfListTopicTargetRoutes200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListTopicTargetRoutes200ResponseFromJSON(json: any): ListTopicTargetRoutes200Response {
    return ListTopicTargetRoutes200ResponseFromJSONTyped(json, false);
}

export function ListTopicTargetRoutes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTopicTargetRoutes200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topicTargetRoutes': !exists(json, 'topicTargetRoutes') ? undefined : ((json['topicTargetRoutes'] as Array<any>).map(NotificationTopicTargetRouteFromJSON)),
    };
}

export function ListTopicTargetRoutes200ResponseToJSON(value?: ListTopicTargetRoutes200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topicTargetRoutes': value.topicTargetRoutes === undefined ? undefined : ((value.topicTargetRoutes as Array<any>).map(NotificationTopicTargetRouteToJSON)),
    };
}

