/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationTargetMetadata
 */
export interface NotificationTargetMetadata {
    /**
     * Webhook URL, must start with "https://".
     * @type {string}
     * @memberof NotificationTargetMetadata
     */
    url: string;
    /**
     * Additional headers to add when Ampersand sends a webhook message
     * @type {{ [key: string]: string; }}
     * @memberof NotificationTargetMetadata
     */
    headers?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the NotificationTargetMetadata interface.
 */
export function instanceOfNotificationTargetMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function NotificationTargetMetadataFromJSON(json: any): NotificationTargetMetadata {
    return NotificationTargetMetadataFromJSONTyped(json, false);
}

export function NotificationTargetMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationTargetMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'headers': !exists(json, 'headers') ? undefined : json['headers'],
    };
}

export function NotificationTargetMetadataToJSON(value?: NotificationTargetMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'headers': value.headers,
    };
}

