/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OperationMetadataResultDetailsWrite } from './OperationMetadataResultDetailsWrite';
import {
    OperationMetadataResultDetailsWriteFromJSON,
    OperationMetadataResultDetailsWriteFromJSONTyped,
    OperationMetadataResultDetailsWriteToJSON,
} from './OperationMetadataResultDetailsWrite';

/**
 * Only present for write operations.
 * @export
 * @interface OperationMetadataResultDetails
 */
export interface OperationMetadataResultDetails {
    /**
     * 
     * @type {OperationMetadataResultDetailsWrite}
     * @memberof OperationMetadataResultDetails
     */
    write?: OperationMetadataResultDetailsWrite;
}

/**
 * Check if a given object implements the OperationMetadataResultDetails interface.
 */
export function instanceOfOperationMetadataResultDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OperationMetadataResultDetailsFromJSON(json: any): OperationMetadataResultDetails {
    return OperationMetadataResultDetailsFromJSONTyped(json, false);
}

export function OperationMetadataResultDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationMetadataResultDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'write': !exists(json, 'write') ? undefined : OperationMetadataResultDetailsWriteFromJSON(json['write']),
    };
}

export function OperationMetadataResultDetailsToJSON(value?: OperationMetadataResultDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'write': OperationMetadataResultDetailsWriteToJSON(value.write),
    };
}

