/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationMetadataResultDetailsWrite
 */
export interface OperationMetadataResultDetailsWrite {
    /**
     * Provider-assigned IDs of successfully created or updated records.
     * @type {Array<string>}
     * @memberof OperationMetadataResultDetailsWrite
     */
    successfulRecordIds?: Array<string>;
}

/**
 * Check if a given object implements the OperationMetadataResultDetailsWrite interface.
 */
export function instanceOfOperationMetadataResultDetailsWrite(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OperationMetadataResultDetailsWriteFromJSON(json: any): OperationMetadataResultDetailsWrite {
    return OperationMetadataResultDetailsWriteFromJSONTyped(json, false);
}

export function OperationMetadataResultDetailsWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationMetadataResultDetailsWrite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'successfulRecordIds': !exists(json, 'successfulRecordIds') ? undefined : json['successfulRecordIds'],
    };
}

export function OperationMetadataResultDetailsWriteToJSON(value?: OperationMetadataResultDetailsWrite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'successfulRecordIds': value.successfulRecordIds,
    };
}

