/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JSONPatchOperation } from './JSONPatchOperation';
import {
    JSONPatchOperationFromJSON,
    JSONPatchOperationFromJSONTyped,
    JSONPatchOperationToJSON,
} from './JSONPatchOperation';

/**
 * 
 * @export
 * @interface PatchObjectConfigContentRequestAllOf
 */
export interface PatchObjectConfigContentRequestAllOf {
    /**
     * The action type for the object config (read, subscribe, or write).
     * @type {string}
     * @memberof PatchObjectConfigContentRequestAllOf
     */
    action: PatchObjectConfigContentRequestAllOfActionEnum;
    /**
     * Array of JSON Patch operations to apply (RFC 6902).
     * Supported operations: add, remove, replace.
     * All paths must start with "/" (e.g., "/schedule", "/selectedFields/phone").
     * @type {Array<JSONPatchOperation>}
     * @memberof PatchObjectConfigContentRequestAllOf
     */
    changes: Array<JSONPatchOperation>;
}


/**
 * @export
 */
export const PatchObjectConfigContentRequestAllOfActionEnum = {
    Read: 'read',
    Subscribe: 'subscribe',
    Write: 'write'
} as const;
export type PatchObjectConfigContentRequestAllOfActionEnum = typeof PatchObjectConfigContentRequestAllOfActionEnum[keyof typeof PatchObjectConfigContentRequestAllOfActionEnum];


/**
 * Check if a given object implements the PatchObjectConfigContentRequestAllOf interface.
 */
export function instanceOfPatchObjectConfigContentRequestAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "changes" in value;

    return isInstance;
}

export function PatchObjectConfigContentRequestAllOfFromJSON(json: any): PatchObjectConfigContentRequestAllOf {
    return PatchObjectConfigContentRequestAllOfFromJSONTyped(json, false);
}

export function PatchObjectConfigContentRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchObjectConfigContentRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'changes': ((json['changes'] as Array<any>).map(JSONPatchOperationFromJSON)),
    };
}

export function PatchObjectConfigContentRequestAllOfToJSON(value?: PatchObjectConfigContentRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'changes': ((value.changes as Array<any>).map(JSONPatchOperationToJSON)),
    };
}

