/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchObjectConfigContentRequestAllOf1OneOf1
 */
export interface PatchObjectConfigContentRequestAllOf1OneOf1 {
    /**
     * The installation ID.
     * Either groupRef or installationId must be provided.
     * @type {string}
     * @memberof PatchObjectConfigContentRequestAllOf1OneOf1
     */
    installationId: string;
}

/**
 * Check if a given object implements the PatchObjectConfigContentRequestAllOf1OneOf1 interface.
 */
export function instanceOfPatchObjectConfigContentRequestAllOf1OneOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "installationId" in value;

    return isInstance;
}

export function PatchObjectConfigContentRequestAllOf1OneOf1FromJSON(json: any): PatchObjectConfigContentRequestAllOf1OneOf1 {
    return PatchObjectConfigContentRequestAllOf1OneOf1FromJSONTyped(json, false);
}

export function PatchObjectConfigContentRequestAllOf1OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchObjectConfigContentRequestAllOf1OneOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'installationId': json['installationId'],
    };
}

export function PatchObjectConfigContentRequestAllOf1OneOf1ToJSON(value?: PatchObjectConfigContentRequestAllOf1OneOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'installationId': value.installationId,
    };
}

