/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProviderApp } from './ProviderApp';
import {
    ProviderAppFromJSON,
    ProviderAppFromJSONTyped,
    ProviderAppToJSON,
} from './ProviderApp';

/**
 * 
 * @export
 * @interface ProviderAppsList
 */
export interface ProviderAppsList {
    /**
     * 
     * @type {Array<ProviderApp>}
     * @memberof ProviderAppsList
     */
    providerApps?: Array<ProviderApp>;
}

/**
 * Check if a given object implements the ProviderAppsList interface.
 */
export function instanceOfProviderAppsList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProviderAppsListFromJSON(json: any): ProviderAppsList {
    return ProviderAppsListFromJSONTyped(json, false);
}

export function ProviderAppsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderAppsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'providerApps': !exists(json, 'providerApps') ? undefined : ((json['providerApps'] as Array<any>).map(ProviderAppFromJSON)),
    };
}

export function ProviderAppsListToJSON(value?: ProviderAppsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'providerApps': value.providerApps === undefined ? undefined : ((value.providerApps as Array<any>).map(ProviderAppToJSON)),
    };
}

