/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadObject
 */
export interface ReadObject {
    /**
     * 
     * @type {string}
     * @memberof ReadObject
     */
    objectName: string;
    /**
     * 
     * @type {string}
     * @memberof ReadObject
     */
    destination: string;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof ReadObject
     */
    selectedFields?: { [key: string]: boolean; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReadObject
     */
    selectedFieldMappings?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ReadObject interface.
 */
export function instanceOfReadObject(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "objectName" in value;
    isInstance = isInstance && "destination" in value;

    return isInstance;
}

export function ReadObjectFromJSON(json: any): ReadObject {
    return ReadObjectFromJSONTyped(json, false);
}

export function ReadObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectName': json['objectName'],
        'destination': json['destination'],
        'selectedFields': !exists(json, 'selectedFields') ? undefined : json['selectedFields'],
        'selectedFieldMappings': !exists(json, 'selectedFieldMappings') ? undefined : json['selectedFieldMappings'],
    };
}

export function ReadObjectToJSON(value?: ReadObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objectName': value.objectName,
        'destination': value.destination,
        'selectedFields': value.selectedFields,
        'selectedFieldMappings': value.selectedFieldMappings,
    };
}

