/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateDestinationRequestDestination } from './UpdateDestinationRequestDestination';
import {
    UpdateDestinationRequestDestinationFromJSON,
    UpdateDestinationRequestDestinationFromJSONTyped,
    UpdateDestinationRequestDestinationToJSON,
} from './UpdateDestinationRequestDestination';

/**
 * 
 * @export
 * @interface UpdateDestinationRequest
 */
export interface UpdateDestinationRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateDestinationRequest
     */
    updateMask: Array<string>;
    /**
     * 
     * @type {UpdateDestinationRequestDestination}
     * @memberof UpdateDestinationRequest
     */
    destination: UpdateDestinationRequestDestination;
}

/**
 * Check if a given object implements the UpdateDestinationRequest interface.
 */
export function instanceOfUpdateDestinationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "updateMask" in value;
    isInstance = isInstance && "destination" in value;

    return isInstance;
}

export function UpdateDestinationRequestFromJSON(json: any): UpdateDestinationRequest {
    return UpdateDestinationRequestFromJSONTyped(json, false);
}

export function UpdateDestinationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDestinationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updateMask': json['updateMask'],
        'destination': UpdateDestinationRequestDestinationFromJSON(json['destination']),
    };
}

export function UpdateDestinationRequestToJSON(value?: UpdateDestinationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updateMask': value.updateMask,
        'destination': UpdateDestinationRequestDestinationToJSON(value.destination),
    };
}

