/* tslint:disable */
/* eslint-disable */
/**
 * Ampersand public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertProjectMembershipRequest
 */
export interface UpsertProjectMembershipRequest {
    /**
     * The builder's ID.
     * @type {string}
     * @memberof UpsertProjectMembershipRequest
     */
    builderId: string;
    /**
     * The builder's role.
     * @type {string}
     * @memberof UpsertProjectMembershipRequest
     */
    role: string;
}

/**
 * Check if a given object implements the UpsertProjectMembershipRequest interface.
 */
export function instanceOfUpsertProjectMembershipRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "builderId" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function UpsertProjectMembershipRequestFromJSON(json: any): UpsertProjectMembershipRequest {
    return UpsertProjectMembershipRequestFromJSONTyped(json, false);
}

export function UpsertProjectMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertProjectMembershipRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'builderId': json['builderId'],
        'role': json['role'],
    };
}

export function UpsertProjectMembershipRequestToJSON(value?: UpsertProjectMembershipRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'builderId': value.builderId,
        'role': value.role,
    };
}

