name: Lint

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run linter
      run: yarn lint:dry
      # If linting fails, the workflow will stop here
    - name: Build project
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status
        yarn build
      # This ensures that if the build fails, the GitHub Action will also fail