on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]

name: Lint

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run linter
      run: yarn lint:dry
